stages:
  - build
  - deploy
  - qa
  - prod

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'

default:
  image: node:latest
  cache: &global_cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - node_modules/
    policy: pull
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store

build:
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      - dist/*

deploy-qa:
   stage: qa
   environment:
    name: staging
    url: https://polite-stone-008c46503.2.azurestaticapps.net
   script:
   - npm install -g @azure/static-web-apps-cli
   - swa deploy -a ./dist --app-name stapp-vue2048-qa -d $AZURE_SWA_QA_TOKEN --env Production

deploy-prod:
   stage: prod
   environment:
    name: production
    url: https://red-ground-077aa6303.2.azurestaticapps.net
   script:
   - npm install -g @azure/static-web-apps-cli
   - swa deploy -a ./dist --app-name stapp-vue2048-prod -d $AZURE_SWA_PROD_TOKEN --env Production